# Generated by Django 5.1.7 on 2025-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('romatic', 'romatic'), ('fantasy', 'fantasy'), ('action', 'action'), ('romantic', 'romantic'), ('documentary', 'documentary'), ('comedy', 'comedy')], max_length=255),
        ),
    ]
