# Generated by Django 5.1.7 on 2025-03-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0005_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_120p',
            field=models.FileField(blank=True, null=True, upload_to='videos/120p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('fantasy', 'fantasy'), ('action', 'action'), ('romantic', 'romantic'), ('documentary', 'documentary'), ('comedy', 'comedy')], max_length=255),
        ),
    ]
