# Generated by Django 5.1.7 on 2025-04-01 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0011_alter_uservideoprogress_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservideoprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='video_app.video'),
        ),
        migrations.AlterUniqueTogether(
            name='uservideoprogress',
            unique_together={('user', 'video')},
        ),
    ]
